version: '3.9'

services:
  db:
    container_name: db_container
    image: postgres:latest
    # restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword 
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - mynetwork

  # pgadmin:
  #   container_name: pgadmin_container
  #   image: dpage/pgadmin4:latest
  #   # restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:
  #     - "5050:80"
  #   networks:
  #     - mynetwork
  #   depends_on:
  #     - db
  
  api:
    container_name: api_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker" 
      ASPNETCORE_URLS: "http://+:80"
    networks:
      - mynetwork

      # web:
  #   build: ../dormy_web
  #   ports:
  #     - 3001:3000
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   networks:
  #     - mynetwork

  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  #   depends_on:
  #     - web
  #   networks:
  #     - mynetwork

volumes:
  pg_data:

networks:
  mynetwork:
    driver: bridge