version: '3.9'

services:
  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5000:80"
  #     #- "5001:443"
  #   depends_on:
  #     - postgres
  #   environment:
  #     ASPNETCORE_ENVIRONMENT: "Development" # Corrected the environment variable here
  #     ASPNETCORE_URLS: "http://+:80"
  #   networks:
  #     - my_network  

  postgres:
    image: pgvector/pgvector:pg16
    container_name: my_postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword 
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    networks:
      - my_network

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: my_pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: my@email.com
  #     PGADMIN_DEFAULT_PASSWORD: my_password
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - postgres
  #   networks:
  #     - my_network  

volumes:
  pg_data:

networks:
  my_network:
    driver: bridge  