namespace Dormy.WebService.Api.Models.Enums
{
    public enum NotificationTypeEnum
    {
        REGISTRATION_CREATION,
        CONTRACT_ACTIVATION,
        VIOLATION_CREATION,
        VIOLATION_UPDATION,
        REQUEST_CREATION,
        REQUEST_UPDATION,
        REQUEST_STATUS_CHANGE,
        PARKING_REQUEST_CREATION,
        PARKING_REQUEST_UPDATION,
        PARKING_REQUEST_STATUS_CHANGE,
        INVOICE_CREATION,
        INVOICE_UPDATION,
        INVOICE_CHANGE_STATUS,
        CONTRACT_CREATION,
        CONTRACT_ACCEPTION,
        CONTRACT_REJECTION,
        CONTRACT_TERMINATION,
        CONTRACT_EXTENSION,
    }
}
